using System;
using System.IO;
using System.Linq;
using UniversalRPG.Plugins;
using UniversalRPG.Web;
using UniversalRPG.Tests.Framework;

namespace UniversalRPG.Tests.Core;

/// <summary>
/// And a game's own plugin JavaScript, run in a sandbox with no doors.
/// </summary>
/// <remarks>
/// <para>
/// <strong>And this is the one place a game's code is executed</strong>, at
/// the user's request and with the risk accepted: a game's menus and windows
/// are what its plugins make them. The sandbox gives the script no file, no
/// network, no process and no <c>require</c>, and bounds it by time, memory
/// and a statement budget.
/// </para>
/// <para>
/// <strong>And it is not a reader of parameters.</strong> The parameters say
/// what the author named a command; only the plugin's own code says what it
/// does with it.
/// </para>
/// </remarks>
public partial class TestMzPluginHost : TestBase
{
    private const string Camellia = "E:/RPGMakerGames/CamelliaCoronation-Win";

    private static bool Vorhanden(string pProjekt) =>
        File.Exists(pProjekt + "/js/plugins.js")
        && File.Exists(pProjekt + "/js/rmmz_core.js");

    /// <summary>
    /// And the engine's own files and the project's plugins execute.
    /// </summary>
    public void Test_DieSandboxLaedtEngineUndPlugins()
    {
        if (!Vorhanden(Camellia))
        {
            return;
        }

        var host = MzPluginHost.Start(Camellia);
        Console.WriteLine($"MZ sandbox: problem=\"{host.Problem}\" "
            + $"engine={host.EngineFiles.Count} loaded={host.LoadedPlugins.Count} "
            + $"failed={host.FailedPlugins.Count}");
        AssertEq(host.Problem, "",
            "the engine's own files all execute in the sandbox");
        AssertTrue(host.EngineFiles.Contains("rmmz_core.js"),
            "the core is among them");
        AssertTrue(host.EngineFiles.Contains("rmmz_windows.js"),
            "and so is the file that holds Window_TitleCommand");

        // **Und die Engine ist danach wirklich da.** A sandbox that ran six
        // files and defined nothing would report the same six files.
        AssertTrue(host.IsDefined("Window_TitleCommand"),
            "the executed engine defines its own title window");
        AssertTrue(host.IsDefined("Scene_Title"),
            "and its own title scene");
        AssertTrue(host.IsDefined("Game_Map"),
            "and its own map");
        AssertTrue(host.IsDefined("$dataSystem"),
            "and the project's own data is a global in there");
    }

    /// <summary>
    /// And which plugins the project switched on is read from its own file.
    /// </summary>
    /// <remarks>
    /// <strong>And a switched-off plugin is not loaded.</strong> The editor
    /// writes every plugin it ever added into <c>plugins.js</c> and marks the
    /// unused ones <c>"status": false</c>; a reader that loaded them all
    /// would run code the author turned off.
    /// </remarks>
    public void Test_NurEingeschaltetePluginsWerdenGeladen()
    {
        const string pluginsJs =
            "// Generated by RPG Maker.\n"
            + "var $plugins =\n[\n"
            + "{\"name\":\"VisuMZ_0_CoreEngine\",\"status\":true,\"parameters\":{}},\n"
            + "{\"name\":\"GALV_CharacterFramesMZ\",\"status\":false,\"parameters\":{}},\n"
            + "{\"name\":\"removeBurgerMenu\",\"status\":true,\"parameters\":{}}\n"
            + "];\n";

        var namen = MzPluginHost.PluginNames(pluginsJs);
        Console.WriteLine("MZ plugin names: " + string.Join(" | ", namen));
        AssertEq(namen.Count, 2, "two of the three are switched on");
        AssertTrue(namen.Contains("VisuMZ_0_CoreEngine"),
            "and the switched-on ones are the ones read");
        AssertTrue(namen.Contains("removeBurgerMenu"), "in the order they stand");
        AssertTrue(!namen.Contains("GALV_CharacterFramesMZ"),
            "a plugin with status false is not loaded");

        AssertEq(MzPluginHost.PluginNames("var $plugins = [];").Count, 0,
            "a project with no plugins has none to load");
        AssertEq(MzPluginHost.ActivePluginNames("Z:/no/such/game").Count, 0,
            "and a project without the file has none either");
    }

    /// <summary>
    /// And the runtime asks the sandbox, and says where the answer came from.
    /// </summary>
    /// <remarks>
    /// <strong>And this is the whole point of the sandbox.</strong> A menu
    /// read out of a plugin's parameters is the names the author typed; a
    /// menu read out of the plugin's own code is what the game would really
    /// show. Measured on Camellia, whose single plugin adds no title command:
    /// the engine's own two are the list either way, so only the reported
    /// source distinguishes them -- and it does.
    /// </remarks>
    public void Test_DieRuntimeFragtDieSandboxUndSagtWoher()
    {
        if (!Vorhanden(Camellia))
        {
            return;
        }

        using var host = new EnginePluginHost(
            BuiltInEnginePluginCatalog.CreateRuntimeRegistry());
        var started = host.Start(new PluginGameInfo
        {
            GameDirectory = Camellia,
            EngineId = EnginePluginIds.RpgMakerMz,
            Generation = "mz",
            DetectorScore = 850,
            PresentTitleScreen = true,
        });
        AssertTrue(started.Success,
            $"the MZ game starts: {started.Error?.Message}");
        if (!started.Success)
        {
            return;
        }

        var runtime = (MzEngineRuntime)host.Runtime!;
        Console.WriteLine($"MZ title before the sandbox: "
            + $"source=\"{runtime.TitleCommandSource}\" "
            + $"commands=[{string.Join(", ", runtime.TitleCommands)}]");
        AssertEq(runtime.TitleCommandSource,
            "the engine's own commands, and nothing else",
            "without a sandbox the title is the engine's own two commands");

        runtime.UsePluginHost(MzPluginHost.Start(Camellia));
        Console.WriteLine($"MZ title after the sandbox: "
            + $"source=\"{runtime.TitleCommandSource}\" "
            + $"commands=[{string.Join(", ", runtime.TitleCommands)}]");
        AssertEq(runtime.TitleCommandSource, "the executed plugins",
            "and with one, the list is the plugins' own answer");
        AssertTrue(runtime.TitleCommands.Contains("New Game"),
            "which still offers a new game");
        AssertTrue(runtime.TitleCommands.Contains("Options"),
            "and still offers the options");

        // **And a title that offers Continue would be lying**, because this
        // runtime has no save file. The engine asks the storage manager, and
        // the sandbox answers that there are none.
        AssertTrue(!runtime.TitleCommands.Contains("Continue"),
            "and it does not offer to continue a game that was never saved");
    }

    /// <summary>
    /// And a plugin suite the sandbox cannot answer for falls back, and says so.
    /// </summary>
    /// <remarks>
    /// <strong>And this is measured rather than assumed.</strong> On the big
    /// project the VisuStella core engine replaces
    /// <c>Window_TitleCommand.makeCommandList</c>, and its replacement throws
    /// inside the sandbox -- so the runtime keeps the parameter list and
    /// reports that it did. A runtime that quietly showed the parameter list
    /// while claiming it came from the plugins would be the dishonest version
    /// of this.
    /// </remarks>
    public void Test_EineSuiteDieDieSandboxUeberfordertFaelltZurueck()
    {
        const string Skies =
            "D:/NextCloud/Games/PornGames/SkiesInflateableAdventure";
        if (!Vorhanden(Skies))
        {
            return;
        }

        using var host = new EnginePluginHost(
            BuiltInEnginePluginCatalog.CreateRuntimeRegistry());
        var started = host.Start(new PluginGameInfo
        {
            GameDirectory = Skies,
            EngineId = EnginePluginIds.RpgMakerMz,
            Generation = "mz",
            DetectorScore = 850,
            PresentTitleScreen = true,
        });
        AssertTrue(started.Success,
            $"the MZ game starts: {started.Error?.Message}");
        if (!started.Success)
        {
            return;
        }

        var runtime = (MzEngineRuntime)host.Runtime!;
        var sandkasten = MzPluginHost.Start(Skies);
        Console.WriteLine($"SKIES sandbox: loaded={sandkasten.LoadedPlugins.Count} "
            + $"failed={sandkasten.FailedPlugins.Count} "
            + $"title answer={(sandkasten.TitleCommands() == null ? "none" : "some")}");
        runtime.UsePluginHost(sandkasten);

        Console.WriteLine($"SKIES title: source=\"{runtime.TitleCommandSource}\" "
            + $"commands=[{string.Join(", ", runtime.TitleCommands)}]");
        AssertEq(runtime.TitleCommandSource, "the plugins' parameters",
            "the parameters are what a title the sandbox cannot answer falls back on");
        AssertTrue(runtime.TitleCommands.Contains("CG Gallery"),
            "and they still name the gallery the plugin adds");
    }
}
