<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UniversalRPG">
      <HintPath>../../project/.godot/mono/temp/bin/Debug/UniversalRPG.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
